bluepyefe/extractor.py

This was causing py3-functional tests to fail in Ubuntu 18.10 and 19.10 platforms

surround round(tend) with try block

---

bluepyefe/extractor.py

When feature extraction was performed on a dataset of a single cell. Efeatures with non-zero values were ignored.
This patch fixes this behaviour.

Fix missing output when dataset of one cell with non-zero efeature

---

bluepyefe/reader.py

In the temporary new NWB reader, allow parsing of both "repetition n" and "repetition 0n" groups (with leading zeros).

Fix reader of NWB containing repetitions with leading zeros

---

bluepyefe/ecode/HyperDePol.py

Use `self.amp_rel` instead of `self.amp2_rel` in the `in_target` function for `HyperDepol`, since it's the hyperpolarization phase that is changed in the ecode protocols

Adjust amplitude use in_target for HyperDepol

---

bluepyefe/cell.py
bluepyefe/extract.py
bluepyefe/protocol.py

- Made the list of efeatures a set in _extract_efeatures_cell to avoid extracting twice the same features if it is asked for several different amplitudes
- Minor changes to the way we check which eCodes name is present in the protocol name.

Minor changes to eCode detection and fix double extraction of some features

---

bluepyefe/ecode/HyperDePol.py

Same as https://github.com/BlueBrain/BluePyEfe/issues/57 but for HyperDepol (adding `toff`)

Complete HyperDepol stimulus parameters

---

bluepyefe/cell.py
bluepyefe/extract.py
bluepyefe/protocol.py
bluepyefe/recording.py
bluepyefe/rheobase.py
bluepyefe/target.py
tests/test_extractor.py
tests/test_protocol.py
tests/test_target.py

In order to allow to extract multiple features with the same feature name from the same recording (e.g. multiple spikecounts for PosCheops), I added an optional `efeature_name` for the targets. If `efeature_name` is given, then the recording can store multiple features of the same type.

Proposal to add optional efeature_names to target

---

.github/workflows/keep-alive.yml

If the last commit is older than 50 days old when the scheduled workflows run, then an empty commit with title 'Empty commit to keep the gihub workflows alive' is made by 'GitHub Actions Bot'.
Remove the dependency to the third party github action to keep the workflows alive.

Custom github action to keep the cron workflows alive

---

.github/workflows/build.yml

Last workflow failed because of a typo. This fixes it.

Fix typo in github workflow

---

bluepyefe/extractor.py
bluepyefe/formats/axon.py
bluepyefe/formats/common.py
bluepyefe/formats/igor.py
bluepyefe/formats/spike2.py
bluepyefe/plottools.py
bluepyefe/tools/tabletools.py
examples/example.ipynb

This PR removes the mutable default arguments found in multiple places in the code.
Additionally it removes some unused imports and unused variables.
References to the bug:
https://docs.python-guide.org/writing/gotchas/
https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/

bugfix: remove mutable default arguments

---

.gitignore
bluepyefe/extra.py
bluepyefe/extractor.py

This PR makes plotting of extra features configurable by the user.
The default behaviour of plotting does not change.
Users simply disable the extra feature plots by calling the following method before running the feature extraction.
`extractor.disable_extra_feature_plots()`
Motivation
-----------
* The feature plots such as `spikerate_tau_slope` are producing an overflowing amount of plots when it is called upon a group of cells, it is very hard to interpret each one of them even for a small amount of cells.
* Those plots are not always desired
* They are computationally expensive
* On the emodels paper notebook disabling them reduces the computational time by **%33**.
* They raise warnings multiple times (for each trace)

add a flag to enable or disable plotting extra feature plots

---

bluepyefe/extractor.py
setup.py

Added a `tqdm` progress bar to the extract function to inform users on the progress and give an estimate on how much remains.
The output looks like this.
83%|████████▎ | 5/6 [00:28<00:05,  5.75s/it]

add progress-bar to the extract function

---

setup.py

Minor update to rid the persistent warning message that is raised each time the version is queried.
BEFORE
```
> python setup.py --version
Warning: 'keywords' should be a list, got type 'tuple'
2.1.2
```
AFTER
```
> python setup.py --version
2.1.2
```

BPE2: address 'keywords' should be a list, got type 'tuple' warning

---

setup.py

Numpy 1.24 has introduced a change that makes igor break. We have to use numpy<1.24 until igor is updated to support numpy1.24+. See https://github.com/wking/igor/pull/4

force numpy<1.24 until igor is updated

---

bluepyefe/ecode/tools.py
tests/test_ecode_tools.py

The base_current function was using the smoothing by default, which is hardcoded to be off in the code (bad bad btw!). I make it follow the main function (and off by default). 
I have traces where the `scipy_signal2d` makes the current = [0, 0, 0, 0], hence completely screwing up the estimation of the current amplitude. 
For example an IV trace with a positive current injection was used as a IV_-20 protocol to estimate the Rin, leading to Rin of -150

Fix smoothing for current amplitude detection

---

bluepyefe/ecode/__init__.py

Hi,
I wanted to add ecode for `Spontaneous` protocol which involves no current injection to the cell.
Thanks,
Darshan

adding spontaneous in ecode init

---

bluepyefe/ecode/SpikeRec.py
bluepyefe/recording.py
bluepyefe/tools.py

computing multiple_decay_time_constant_after_stim

Add multi_stim_start and multi_stim_end to the efel_settings when

---

.readthedocs.yml

motivation: readthedocs uses python3.7 but igor2 requires python>=3.8
Precising python version in new .readthedocs.yml file should solve this problem and make readthedocs work once again.

add readthedocs.yml file

---

.readthedocs.yml
AUTHORS.txt

Readthedocs fails with module import error because it cannot find bluepyefe. This should fix it.

Make readthedocs install bluepyefe

---

.readthedocs.yml
requirements_docs.txt
setup.py

readthedocs now fails with missing sphinx-bluebrain-theme requirement. This should fix it.

Readthedocs install

---

bluepyefe/ecode/sAHP.py

When user has info about step start and end, s/he should inform it to bluepyefe, because automatic step detection cannot always properly detect steps, especially when the trace is noisy and the step amplitude is low.
This PR fixes step detection for a particular trace that made bluepyefe crash. The number 2.0 is ad hoc (as was previously 4.5) and fine tuned by hand to allow a maximum of traces to be properly detected. I tested this on 211 traces from the rat primary somatosensory cortex recorded by lnmc.
With 2.0, only 3 traces had ton and toff not properly detected, and bluepyefe did not crash. With a value less than 2.0, we start having tmid and tmid2 values not being properly detected for several traces. With a value larger than 2.0, we have more ton and toff not properly detected.

modify step threshold in step detection of sAHP

---

bluepyefe/plotting.py

When using the built-in map() function, force immediate evaluation by converting its lazy iterator result to a list. This ensures that the _plot function is executed immediately when using the standard map() but remains unchanged for other mappers.

Force evaluation for built-in map()

---

bluepyefe/tools.py

numpy.float_ is deprecated in numpy2: https://numpy.org/devdocs/numpy_2_0_migration_guide.html

Make BluePyEfe compatible with numpy2

---

bluepyefe/cell.py
bluepyefe/nwbreader.py
bluepyefe/reader.py

- also match ecodes with non-matching capital/lower letters, e.g. IDRest with IDrest

select nwb traces according to v_file field

---

bluepyefe/nwbreader.py

* To get `protocol_name` from `stimulus_description` entries to allow ecodes names other than `Step`
* Preserves the default `protocol_name` `Step` for Scala files
* Tested for collaborator files for hippocampus and straitum

allow stimulus_description in ScalaNWBReader

---

bluepyefe/extract.py

So that we can fetch those paths with other software, e.g. BPEM, and so that we can account for any path change in BPE

Put output pickle path into fetachable functions

---

README.rst
pyproject.toml

This should fix the build action that failed for previous PR

remove PyPi uncompatible 'raw' in readme
